# Generated by Django 4.2.13 on 2024-06-26 23:26

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('ambulance_name', models.CharField(max_length=50, null=True)),
                ('current_location', models.CharField(max_length=100, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('response_rate', models.IntegerField(default=0)),
                ('driver_name', models.CharField(max_length=50, null=True)),
                ('hospital_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(max_length=40, null=True)),
                ('ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ambulance_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='ambulance_image')),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('pay_rate', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='machinery_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='owner_post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='machinery_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='is_hospital',
            field=models.BooleanField(default=False, verbose_name='Is hospital'),
        ),
        migrations.DeleteModel(
            name='Machinery',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Owner_post',
        ),
        migrations.AddField(
            model_name='hospitalpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ambulance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance'),
        ),
    ]
